const clauses = [
  {
    id: 1,
    idContrat: 1,
    ori: 'PAR',
    des: 'TLS',
    cdr: 'C',
    farebasis: 'FULL-FLEX',
    cie: 'AF',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 23,
  },
  {
    id: 2,
    idContrat: 2,
    ori: 'PAR',
    des: 'TLS',
    cdr: 'D',
    farebasis: 'SEMI-FLEX',
    cie: 'AF',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 15,
  },
  {
    id: 3,
    idContrat: 2,
    ori: 'PAR',
    des: 'TLS',
    cdr: 'Y',
    //farebasis: '',
    upgradable: 1,
    cie: 'AF',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 4,
},
  {
    id: 4,
    idContrat: 1,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'C',
    farebasis: 'FULL-FLEX',
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 35,
  },
  {
    id: 5,
    idContrat: 1,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'D',
    farebasis: 'SEMI-FLEX',
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 22,
  },
  {
    id: 11,
    idContrat: 1,
    ori: 'TLS',
    des: 'MUC',
    upgradable: 1,
    cdr: 'Y',
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 22,
  },
  {
    id: 36,
    idContrat: 3,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 5,
  },
  {
    id: 7,
    idContrat: 3,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'DL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 3,
  }, 
  {
    id: 41,
    idContrat: 4,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 8,
  },
  {
    id: 51,
    idContrat: 5,
    ori: 'TLS',
    des: 'MAD',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 2,
  },
  {
    id: 61,
    idContrat: 6,
    ori: 'TLS',
    des: 'MUC',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 7,
  },
  {
    id: 61,
    idContrat: 6,
    ori: 'TLS',
    des: 'MUC',
    cdr: 'Z',
    farebasis: '',
    upgradable: 1,
    cie: 'LH',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 1,
  },
];

//module.exports = clauses;

const getListeClauses = (contratId) => {
  var liste = [];
  clauses.forEach(clause => {
    //console.log("clause " + clause.id); 
    if(clause.idContrat == contratId) {
      liste.push(clause);
    }
  });
  return liste;
};

module.exports = { clauses, getListeClauses };
